### ISSUE TITLE
No Longer able to batch change TV values

### ISSUE THREAD

**Issue by joeke** [Sterc/Batcher#18]
From: https://github.com/splittingred/Batcher/issues/30

When trying to batch change the TV values of a specific template the area where options are meant to be selectable nothing appears.

Checked broswer console and there aren't any error messages. Tried in Safari, Firefox and Chrome. Disabled AdBlock as well.

MODX 2.2.14-pl traditional + Batcher 1.1.1 + PHP 5.4.25

[0.25]

**Comment by gpsietzema** [comment]
We'll remove it from it featureset, since it doesn't add anything.

[1]

**Comment by EasterPeanut** [comment]
@gpsietzema Removed this functionality.
