### ISSUE TITLE
bug version 2.0.0

### ISSUE THREAD

**Issue by systemshock89** [Sterc/Batcher#27]
when I update from version 1 to version 2.0.0, I see bug:
empty tab resources in Batcher. 
In console js error: "Uncaught SyntaxError: Unexpected token <"

When trying to search for a filter js error "Uncaught SyntaxError: Unexpected token <"

**Comment by systemshock89** [comment]
Parse error</b>:  syntax error, unexpected T_DOUBLE_ARROW in <b>D:\projects\modx.local\core\components\batcher\processors\mgr\resource\getlist.class.php</b> on line <b>69

line 69:
 $filterQuery = [$filterField . ':' . $filterType => $filterValue];

**Comment by joeke** [comment]
What PHP version are you using? I think that error is caused by PHP versions 5.3 and below.

**Comment by systemshock89** [comment]
yes, I already understood it myself. Thank you.
It is necessary to use PHP 5.4 or up
