### ISSUE TITLE
double quotes in pagetitle result in a blank screen

### ISSUE THREAD

**Issue by joeke** [Sterc/Batcher#9]
from: https://github.com/splittingred/Batcher/issues/12

to reproduce this:
1. create a template
2. create a resource using that template and double quotes " in the pagetitle
3. go to batcher > templates tab
4. check your template
5. choose Change TV Values

voilá - there went batcher :)

Tested in latest Chrome, Safari & FF4. 
btw single quotes ' in the pagetitle are fine.

[1]

**Comment by EasterPeanut** [comment]
@gpsietzema removed the functionality to change the TV values in #18
